name: ci
on:
  pull_request_target:
    branches:
      - master
    paths:
      - "client/src/**"
      - "server/src/**"
jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: install top level dependencies
        run: npm install
      - name: building client side
        run: npm run build --prefix client
      - name: run test
        run: npm run test
