name: repack ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install top level dependencies
        run: npm install
      - name: install client and server side dependencies
        run: npm run install
      - name: building client side
        run: npm run build --prefix client
      - name: run test
        run: npm run test
